# this is workflow name
name: Hello

#runs on a trigger
on:
  #workflowdispatch - when we manually run the action
  #workflow_dispatch: 

  #push - it will automaticall ruun the action
  push:
    branches: [main]

  #paths - it will run only if the condition matches
    paths:
      - '**.html'
      - '**.yml'

#these are jobs insode the workflow
jobs:

  #this is name of the job
  greet:
    #this is github runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "Hello User"

      - name: say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what is the version of python, docker
        run: docker --version && python --version





